### ISSUE TITLE
problems with TypeScript.git#release-1.5

### ISSUE THREAD

**Issue by PatrickJS** [blakeembrey/typescript-simple-loader#3]
``` coffee
"typescript": "git://github.com/Microsoft/TypeScript.git#release-1.5"
```

```
Module build failed: TypeError: Cannot read property 'map' of undefined
    at createService (/Users/patrick/Documents/AngularClass/angular2-webpack-starter/node_modules/typescript-simple-loader/dist/typescript-simple-loader.js:53:13)
    at getLoaderInstance (/Users/patrick/Documents/AngularClass/angular2-webpack-starter/node_modules/typescript-simple-loader/dist/typescript-simple-loader.js:140:19)
    at Object.loader (/Users/patrick/Documents/AngularClass/angular2-webpack-starter/node_modules/typescript-simple-loader/dist/typescript-simple-loader.js:12:14)
 @ multi angular2
```

**Comment by blakeembrey** [comment]
Cheers, I'll take a look. From the first look, I think that's the `files` array it's trying to map over - but I should get rid of this crash.

**Comment by blakeembrey** [comment]
@gdi2290 I just released https://github.com/blakeembrey/typescript-simple-loader/releases/tag/v0.2.0 which run some tests from the tag you provided. Give it a go?

**Comment by PatrickJS** [comment]
kool, I'll try it out
